// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-estimates.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) {
    throw new Error("SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is required");
  }
  return key;
}
function supabaseForUser(ctx) {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}

// src/lib/mcp/tools/list-estimates.ts
var list_estimates_default = defineTool({
  name: "list_estimates",
  title: "List estimates",
  description: "List the signed-in user's estimates with status, client, project name and totals. Optionally filter by status or search text.",
  inputSchema: {
    status: z.string().optional().describe("Filter by estimate status, e.g. Draft, Ready, Sent, Accepted."),
    search: z.string().optional().describe("Case-insensitive match on project name or client name."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("estimates").select(
      "estimate_id, project_name, client_name, status, project_type, project_category, city, state, sqft, subtotal, total_low, total_high, version, completeness_score, calc_status, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    if (search) query = query.or(`project_name.ilike.%${search}%,client_name.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, estimates: data ?? [] });
  }
});

// src/lib/mcp/tools/get-estimate.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_estimate_default = defineTool2({
  name: "get_estimate",
  title: "Get estimate detail",
  description: "Get one estimate by its estimate_id, including scope, totals, risk numbers and its line items grouped by phase.",
  inputSchema: {
    estimate_id: z2.string().trim().min(1).describe("The estimate_id, e.g. EST-0014.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ estimate_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data: estimate, error } = await supabase.from("estimates").select(
      "estimate_id, project_name, client_name, client_email, project_address, city, state, zip, status, project_type, project_category, scope_class, job_complexity, sqft, finish_level, included_trades, labor_subtotal, material_subtotal, subtotal, risk_cost_low, risk_cost_high, overall_risk_level, overhead_pct, profit_pct, contingency_pct, total_low, total_high, version, last_revision_summary, completeness_score, calc_status, ai_scope, public_notes, updated_at"
    ).eq("estimate_id", estimate_id).maybeSingle();
    if (error) return errorResult(error.message);
    if (!estimate) return errorResult(`No estimate found with estimate_id ${estimate_id}.`);
    const { data: lines, error: linesError } = await supabase.from("estimate_line_items").select(
      "line_id, phase, description, unit, qty, labor_total, material_total, line_total, source, locked"
    ).eq("estimate_id", estimate_id).order("phase", { ascending: true });
    if (linesError) return errorResult(linesError.message);
    return jsonResult({ estimate, line_items: lines ?? [], line_item_count: lines?.length ?? 0 });
  }
});

// src/lib/mcp/tools/list-jobs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_jobs_default = defineTool3({
  name: "list_jobs",
  title: "List jobs",
  description: "List the signed-in user's jobs with status, schedule window, address and crew lead. Optionally filter by job status or scheduled date range.",
  inputSchema: {
    job_status: z3.string().optional().describe("Filter by job status, e.g. Draft, Scheduled, Confirmed, In Progress, Completed."),
    starts_after: z3.string().optional().describe("ISO date/time lower bound on start_datetime."),
    starts_before: z3.string().optional().describe("ISO date/time upper bound on start_datetime."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ job_status, starts_after, starts_before, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("jobs").select(
      "job_id, estimate_id, job_title, job_status, property_address, start_datetime, end_datetime, crew_lead_name, client_name, scheduling_ready, updated_at"
    ).order("start_datetime", { ascending: true, nullsFirst: false }).limit(limit ?? 25);
    if (job_status) query = query.eq("job_status", job_status);
    if (starts_after) query = query.gte("start_datetime", starts_after);
    if (starts_before) query = query.lte("start_datetime", starts_before);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, jobs: data ?? [] });
  }
});

// src/lib/mcp/tools/list-contracts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_contracts_default = defineTool4({
  name: "list_contracts",
  title: "List contracts",
  description: "List the signed-in user's contracts with contract status, baseline and current financials, percent complete and margin health flags.",
  inputSchema: {
    contract_status: z4.string().optional().describe("Filter by contract status."),
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contract_status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("contracts").select(
      "contract_id, estimate_id, contract_status, baseline_contract_value, baseline_margin_pct, net_contract_value, percent_complete, projected_final_cost, projected_final_profit, margin_current_pct, profit_fade_flag, risk_quadrant, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (contract_status) query = query.eq("contract_status", contract_status);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, contracts: data ?? [] });
  }
});

// src/lib/mcp/tools/search-cost-library.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^4.4.3";
var search_cost_library_default = defineTool5({
  name: "search_cost_library",
  title: "Search cost library",
  description: "Search the signed-in user's Cost Library reference pricing by trade, project type or description text.",
  inputSchema: {
    trade: z5.string().optional().describe("Filter by trade/phase, e.g. Framing, Drywall."),
    project_type: z5.string().optional().describe("Filter by project type, e.g. Bath, Kitchen, Full Rehab."),
    search: z5.string().optional().describe("Case-insensitive match on the item description."),
    limit: z5.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trade, project_type, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    let query = supabaseForUser(ctx).from("cost_library").select(
      "id, trade, project_type, description, unit_label, qty_rule, labor_unit_cost, material_unit_cost, labor_hours_per_unit, default_included, active, last_updated"
    ).order("trade", { ascending: true }).limit(limit ?? 25);
    if (trade) query = query.eq("trade", trade);
    if (project_type) query = query.eq("project_type", project_type);
    if (search) query = query.ilike("description", `%${search}%`);
    const { data, error } = await query;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, items: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "qzkyqpzcwqohzskqqqau";
var mcp_default = defineMcp({
  name: "estimate-genius",
  title: "Estimate Genius",
  version: "0.1.0",
  instructions: "Read-only tools for the TVIK Estimator system. Use list_estimates / get_estimate for estimate scope, line items and totals; list_jobs for scheduling; list_contracts for contract financials; search_cost_library for reference pricing. All data is scoped to the signed-in user. These tools never modify estimates, contracts or jobs.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_estimates_default, get_estimate_default, list_jobs_default, list_contracts_default, search_cost_library_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
